[telegram]
chat_id = "123456"
flush_seconds = 5

[match]
1 = {field="PRIORITY", value="5"}

[deny]
1 = {field="SYSLOG_IDENTIFIER", value="aardvark-dns|scrutiny|caddy|overseerr|winbindd|sabnzbd|calibre|samba-dcerpcd|rpcd_lsad|rpcd_mdssvc|rpcd_classic|rpcd_winreg"}
2 = {field="MESSAGE", value=[
	"RequiresMountsFor=|podman-.*\\.service",
	"unix_listener: cannot bind to path /run/user/0/gnupg/S.gpg-agent",
	"auto-fix-vscode-server.service: Failed to open",
	"nixos-rebuild-switch-to-configuration.service.*No such file or directory",
], rule="any"}
3 = [
	{field="SYSLOG_IDENTIFIER", value="plex"},
	{field="MESSAGE", value=[
		"Unable to open: No such file or directory",
		"Connection to .* closed by remote host."
	], rule="any"}
]
4 = [
	{field="SYSLOG_IDENTIFIER", value="private-wg"},
	{field="MESSAGE", value=[
		"Loading configuration\\.\\.\\.",
		"Configuration loaded\\.",
		"Config saving\\.\\.\\.",
		"Config saved\\.",
		"Config syncing\\.\\.\\.",
		"Config synced\\.",
		"changing ownership of '\\/config\\/wg_confs': Read-only file system",
		"\\/config\\/wg_confs\\/wg0\\.conf' is world accessible",
		"ip link add wg0 type wireguard",
		"wg setconf wg0 \\/dev\\/fd\\/63",
		"ip -4 address add 10.254.33.0\\/24 dev wg0",
		"ip link set mtu 1420 up dev wg0",
	], rule="any"}
]

[allow]