[telegram]
chat_id = "123456"
flush_seconds = 5

[match]
1 = {field="PRIORITY", value=[
	"5",
	"4",
	"3",
	"2",
	"1",
	"0",
]}

[deny]
1 = {field="SYSLOG_IDENTIFIER", value="smbd"}
2 = {field="MESSAGE", value=[
	"RequiresMountsFor=|podman-.*\\.service",
], rule="any"}
3 = [
	{field="SYSLOG_IDENTIFIER", value="plex"},
	{field="MESSAGE", value=[
		"Unable to open: No such file or directory",
		"Connection to .* closed by remote host."
	], rule="any"}
]
4 = [
	{field="SYSLOG_IDENTIFIER", value="vpn"},
	{field="MESSAGE", value=[
		"Loading configuration\\.\\.\\.",
		"Configuration loaded\\.",
		"Config saving\\.\\.\\.",
		"Config saved\\.",
		"Config syncing\\.\\.\\.",
		"Config synced\\.",
	], rule="any"}
]

[allow]